{% set name = "spacy" %}
{% set version = "3.2.1" %}
{% set sha256sum = "f6ebac511627740a8ca2b117b91ef5515c8f0b2fb117a69ebe01d010dd4fc53c" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256sum }}

build:
  number: 2
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - pip  {{ pip }}
    - python  {{ python }}
    - setuptools {{ setuptools }}     
    - numpy {{ numpy }} 
    - wheel
    - cython {{ cython }}
    - cymem {{ cymem }} 
    - preshed {{ preshed }}
    - murmurhash {{ murmurhash }}
    - thinc {{ thinc }} 
    - cython-blis {{ cython_blis }}
    - pydantic {{ pydantic }}
  run:
    - python {{ python }}
    - numpy {{ numpy }}
    - spacy-legacy {{ spacy_legacy }}
    - murmurhash {{ murmurhash }}
    - cymem {{ cymem }} 
    - preshed {{ preshed }} 
    - thinc {{ thinc }}
    - cython-blis {{ cython_blis }}
    - requests {{ requests }} 
    - wasabi {{ wasabi }} 
    - srsly {{ srsly }}
    - catalogue {{ catalogue }}
    - typer {{ typer }}
    - tqdm {{ tqdm }}
    - pathy {{ pathy }}
    - pydantic {{ pydantic }}
    - setuptools {{ setuptools }}
    - packaging >=20.0
    - typing_extensions {{ typing_extensions }}  # [py<38] 
    - jinja2
    - langcodes
    - spacy-loggers {{ spacy_loggers }}

test:
  requires:
    - pytest
    - pytest-timeout
    - mock
    - hypothesis
  imports:
    - spacy
  commands:
    - python -m pytest --tb=native -k "not test_get_third_party_dependencies" --pyargs {{ name }}
    
about:
  home: https://spacy.io/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Industrial-strength Natural Language Processing
  description: |
    spaCy is a library for advanced natural language processing in Python and
    Cython.
  doc_url: https://spacy.io
  dev_url: https://github.com/explosion/spaCy

extra:
  recipe-maintainers:
    - open-ce/open-ce-dev-team
