{% set name = "spacy" %}
{% set version = "2.3.4" %}
{% set sha256sum = "a5c8805759114aac3a1db1b20f42af1124da5315be903ccb4c472cc8452393fb" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256sum }}

build:
  number: 3
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  build:
    - pip {{ pip }}
    - {{ compiler('cxx') }}
    # Use pins to control cos6/cos7 match
    - libgcc-ng  {{ libgcc }}
    - libstdcxx-ng  {{ libstdcxx }}
  host:
    - pip  {{ pip }}
    - python  {{ python }}
    - numpy {{ numpy }} 
    - wheel {{ wheel }} 
    - cython {{ cython }}
    - cymem {{ cymem }} 
    - preshed {{ preshed }}
    - murmurhash {{ murmurhash }}
    - thinc {{ thinc }} 
    # Use pins to control cos6/cos7 match
    - libgcc-ng  {{ libgcc }}
    - libstdcxx-ng  {{ libstdcxx }}
  run:
    - python {{ python }}
    - {{ pin_compatible('numpy', min_pin='1.15.x') }}
    - murmurhash {{ murmurhash }}
    - cymem {{ cymem }} 
    - preshed {{ preshed }} 
    - thinc {{ thinc }}
    - cython-blis {{ cython_blis }}
    - plac {{ plac }}
    - requests {{ requests }} 
    - wasabi {{ wasabi }} 
    - srsly {{ srsly }}
    - jsonschema
    - catalogue {{ catalogue }}

test:
  requires:
    - pytest
    - mock
    # Use pins to control cos6/cos7 match
    - libgcc-ng  {{ libgcc }}
    - libstdcxx-ng  {{ libstdcxx }}
  imports:
    - spacy

about:
  home: https://spacy.io/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Industrial-strength Natural Language Processing
  description: |
    spaCy is a library for advanced natural language processing in Python and
    Cython.
  doc_url: https://spacy.io
  dev_url: https://github.com/explosion/spaCy

extra:
  recipe-maintainers:
    - open-ce/open-ce-dev-team
